# TAG=v2.0
# docker buildx build --platform=linux/amd64 -t david62243/webplanes:${TAG}-day0 -f Dockerfile-day0 .   # Use this line to complie on ARM based Mac
# docker build -t david62243/webplanes:${TAG}-day0 -f Dockerfile-day0 .
# docker push david62243/webplanes:${TAG}-day0
#
# docker run -it --entrypoint /bin/bash -p 8080:8080 david62243/webplanes:v2.0-day0  
# export PLANES_NUM_DAYS_DATA=1
# export PLANES_PATH_TO_DATA="/home/ubuntu/data/"
# java -jar webplanes.jar 
#
# docker run -it -e PLANES_NUM_DAYS_DATA=1 -e PLANES_PATH_TO_DATA="/home/ubuntu/data/" -p 8080:8080  david62243/webplanes:v2.0-day0 
#
# Build stage
#

FROM maven:3.8.5-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -DskipTests=true -f /home/app/pom.xml install

#
# Package stage
#
FROM openjdk:22-ea-17-slim
RUN useradd -u 1000 -ms /bin/bash ubuntu

COPY --from=build /home/app/target/webplanes-0.0.1-SNAPSHOT.jar /home/ubuntu/webplanes.jar
COPY --chown=ubuntu:ubuntu data /home/ubuntu/data
USER ubuntu
WORKDIR /home/ubuntu
EXPOSE 8080
ENTRYPOINT ["java","-jar","webplanes.jar"]
