---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webplanes
  namespace: simulators
  labels:
    app: webplanes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webplanes
  template:
    metadata:
      labels:
        app: webplanes
    spec:
      containers:
        - name: webplanes
          image: david62243/webplanes:v1.0
          #command: ["sleep", "3650d"]
          command: ["java", "-jar", "-DPLANES_NUM_DAYS_DATA=7", "-DPLANES_PATH_TO_DATA=/data/lat88_csv3/", "-Dserver.port=8080", "/opt/webplanes/webplanes-0.0.1-SNAPSHOT.jar"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '500m'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: planes