apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websats
spec:
  defaultBackend:
    service:
      name: websats
      port:
        number: 80
  rules:
    - host: websats3.westus2.cloudapp.azure.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: websats
              port:
                number: 80